name: 'yfinance_analytics'
version: '1.0.0'

profile: 'yfinance_analytics_stack'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    bronze:
      +materialized: view, 
      +schema: bronze,
      +tags: ['bronze', 'daily_ingestion']

    silver:
      +materialized: incremental,
      +schema: silver,
      +tags: ['cleaned', 'historical']
    gold:
      +materialized: table,
      +schema: gold,
      +tags: ['analytics', 'bi_ready']