version: 1

sources:
  - name: postgres
    schema: public
    tables:
      - name: stocks
        description: "Esse modelo contém os preços históricos das ações de várias empresas."
        columns:
          - name: date
            description: "A data do registro do preço da ação."
          - name: ticker
            description: "O símbolo do ticker da ação (por exemplo, AAPL, MSFT)."
          - name: open
            description: "O preço de abertura da ação na data dada."
          - name: close
            description: "O preço de fechamento da ação na data dada."
          - name: high
            description: "O preço mais alto da ação na data dada."
          - name: low
            description: "O preço mais baixo da ação na data dada."
          - name: volume
            description: "O volume de negociação da ação na data dada."