version: 1

models:
  - name: stg_stocks
    description: "Esse modelo representa os dados de preço de ações limpos e transformados da tabela de origem 'stocks'. Inclui colunas renomeadas para melhor legibilidade e é materializado como uma view no schema 'silver'."
    columns:
      - name: date
        description: "A data do registro do preço da ação."
      - name: ticker
        description: "O símbolo do ticker da ação (por exemplo, AAPL, MSFT)."
      - name: open_price
        description: "O preço de abertura da ação na data dada."
      - name: close_price
        description: "O preço de fechamento da ação na data dada."
      - name: high_price
        description: "O preço mais alto da ação na data dada."
      - name: low_price
        description: "O preço mais baixo da ação na data dada."
      - name: trading_volume
        description: "O volume de negociação da ação na data dada."